<!-- Hot deals Template Homepage -->
<?php
$totalPerPage = ($this->show_total) ? $this->show_total : 3;
$visibility = array(
Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$storeId = Mage::app()->getStore()->getId();
$_productCollection = Mage::getResourceModel('reports/product_collection')
->addAttributeToSelect('*')
->setStoreId($storeId)
->addStoreFilter($storeId)
->addAttributeToFilter('visibility', $visibility)
->addAttributeToFilter('featured', true)
->setOrder('created_at', 'desc')
->addAttributeToSelect('status')
->setPageSize($totalPerPage);

Mage::getSingleton('catalog/product_status') -> addVisibleFilterToCollection($_productCollection);
Mage::getSingleton('cataloginventory/stock') -> addInStockFilterToCollection($_productCollection);
Mage::getSingleton('catalog/product_visibility') -> addVisibleInSearchFilterToCollection($_productCollection);
?>

<div id="shop-great-deals">
<h2 >Shop Great Deals</h2>
<?php $_collectionSize = $_productCollection->count() ?>
<div class="featured-product-grid" id="product-list-table">

<?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php if ($i++%6==0): ?>
<?php endif ?>


<!-- Start Decompressing code -->
<li>
	<a href="<?php echo $_product->getProductUrl() ?>"> 
		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" width="200px" height="133px" />
	</a>
        <h3>
        	<a href="<?php echo $_product->getProductUrl() ?>">
        	<?php echo substr($this->htmlEscape($_product->getName()),0,31)?></a>
        </h3>
                <div class="hot-pro-des"><?php echo $this->helper('checkout')->formatPrice($_product->getPrice()) ?></div>
</li>
<!-- Start Decompressing code -->


<ul>
<li>
		<p class="product-image">
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
		<img style="height:190px; width:300px;" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170, 170); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
		</a>
		</p>

		<h3><a href="<?php echo $_product->getProductUrl() ?>">
		<?php echo substr($this->htmlEscape($_product->getName()),0,31)?></a></h3>
		<div class="short-descript"> <?php echo substr($_product->getShortDescription(),0,50); ?></div>

	<span class="new"><?php echo $this->helper('checkout')->formatPrice($_product->getPrice()) ?></span>
</li>

		<?php if ($i%3==0 && $i!=$_collectionSize): ?>
		<?php endif ?><?php endforeach ?>
		<?php for($i;$i%3!=0;$i++): ?>
	<li class="empty-product">&nbsp;</li><?php endfor ?><?php if ($i%3==0): ?>
		<?php endif ?>
</div><!-- End of Featured Products-->

	<script type="text/javascript">decorateTable('product-list-table')</script>
</div>